# MCP Knowledge Hub - EC2 instance (CloudFormation)
# Creates: Security Group + EC2 instance named mcp-server-instance
# Usage: aws cloudformation create-stack --stack-name mcp-hub-infra --template-body file://infra/mcp-ec2.yaml --parameters ParameterKey=KeyName,ParameterValue=YOUR_KEY_NAME

AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance for MCP Knowledge Hub (mcp-server-instance)"

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 Key Pair to enable SSH access
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    Description: EC2 instance type
  AmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Amazon Linux 2023 AMI (latest via SSM)
  AllowedSSHCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR allowed for SSH (22). Restrict to your IP in production.
  CognitoUserPoolName:
    Type: String
    Default: mcp-knowledge-hub-users
    Description: Name of the Cognito User Pool for MCP JWT (optional; used for /mcp auth).
  CognitoCreateUserPool:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Create Cognito User Pool and App Client for MCP HTTP JWT auth. Set false to use an existing User Pool.

Conditions:
  CreateCognito: !Equals [!Ref CognitoCreateUserPool, "true"]

Resources:
  # Cognito User Pool para JWT del endpoint /mcp (Cursor, clientes HTTP streamable)
  MCPUserPool:
    Type: AWS::Cognito::UserPool
    Condition: CreateCognito
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolTags:
        Project: MCP-Knowledge-Hub

  MCPUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Condition: CreateCognito
    DependsOn: MCPUserPool
    Properties:
      ClientName: mcp-gateway-client
      UserPoolId: !Ref MCPUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 60
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  MCPInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MCP Knowledge Hub EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHCIDR
          Description: SSH
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS
      Tags:
        - Key: Name
          Value: mcp-server-instance-sg

  MCPInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MCPInstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: mcp-server-instance
    Metadata:
      AWS::CloudFormation::Designer:
        id: MCPInstance

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref MCPInstance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"
  PublicIP:
    Description: Public IP of the instance (use for SSH and browser)
    Value: !GetAtt MCPInstance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"
  URL:
    Description: Example URL once stack is running
    Value: !Sub "http://${MCPInstance.PublicIp}"
  # Cognito (solo si CognitoCreateUserPool=true). Añade estos valores al .env del gateway en la EC2.
  CognitoUserPoolId:
    Condition: CreateCognito
    Description: Cognito User Pool ID (COGNITO_USER_POOL_ID en .env del gateway)
    Value: !Ref MCPUserPool
    Export:
      Name: !Sub "${AWS::StackName}-CognitoUserPoolId"
  CognitoAppClientId:
    Condition: CreateCognito
    Description: Cognito App Client ID (COGNITO_APP_CLIENT_ID en .env del gateway)
    Value: !Ref MCPUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-CognitoAppClientId"
  CognitoRegion:
    Condition: CreateCognito
    Description: Región del User Pool (COGNITO_REGION en .env del gateway)
    Value: !Ref AWS::Region
    Export:
      Name: !Sub "${AWS::StackName}-CognitoRegion"
  CognitoIssuerUrl:
    Condition: CreateCognito
    Description: Issuer URL para JWT (opcional; el gateway construye JWKS desde región + User Pool ID)
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${MCPUserPool}"
    Export:
      Name: !Sub "${AWS::StackName}-CognitoIssuerUrl"
